name: heroicons
description: HeroIcons set of SVG icons in your Flutter app. Both outlined & solid icon version are available.
version: 0.6.0
homepage: https://github.com/vaetas/heroicons

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.1
  path: ^1.8.2

dev_dependencies:
  code_builder: ^4.1.0
  dart_style: ^2.2.3
  recase: ^4.0.0

flutter:
  assets:
    - assets/
    - assets/outline/
    - assets/solid/
